### ISSUE TITLE
[Milestone Tracker] Implementation of Manual CPFP for Revault Managers

### ISSUE THREAD

**Issue by Zshan0** [revault/revault-gui#370]
Corresponding to https://github.com/revault/revaultd/issues/411, this issue is to update the progress that will be made on the implementation of manual CPFP command for managers on the `revault-gui` side. The API on `revaultd`'s side has been fixed allowing the work on `revault-gui` to start. The implementation can be broken down as follows:

- [ ] Implementation of the `revaultd` caller on `revault-gui`
- [ ] Tests for the caller
- [ ] UI addition that will trigger manual CPFP
- [ ] Tests for the UI

Due to the assumption that `revaultd` API works independently of the GUI, it can be assumed that proper functionality of both `revaultd` and `revault-gui` sides of manual CPFP API implies that the overall API works well too.
